---
# Source: catalyst/templates/pvc-workspace.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalyst-workspace
  namespace: catalyst-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
