---
# Source: catalyst/templates/core.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalyst-core-service
  namespace: catalyst-local
spec:
  selector:
    app: catalyst-core
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: catalyst/templates/core.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-core
  namespace: catalyst-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalyst-core
  template:
    metadata:
      labels:
        app: catalyst-core
    spec:
      containers:
        - name: core
          image: catalyst/core:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BROKER_URL
              value: tcp://catalyst-broker-service:1883
            - name: DATABASE_URL
              value: postgres://catalyst:devpassword@catalyst-db-service:5432/catalyst_core
            - name: LLM_ENDPOINT
              value: "http://host.docker.internal:11434/v1" # Localhost LLM access from container
            - name: WORKSPACE_ROOT
              value: "/workspace"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: workspace-storage
              mountPath: /workspace
      volumes:
        - name: config-volume
          configMap:
            name: catalyst-core-config
        - name: workspace-storage
          persistentVolumeClaim:
            claimName: catalyst-workspace
